services:
  - type: worker
    name: bitcoin-alert-bot
    env: python
    plan: free
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
